package com.foodrec.service;

import com.foodrec.model.Disease;
import com.foodrec.model.FoodRecommendation;
import com.foodrec.util.APIClient;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Service
public class GeminiAIService extends AIService {

    @Value("${gemini.api.key}")
    private String geminiApiKey;

    public GeminiAIService(APIClient apiClient) {
        super(apiClient);
        // PERUBAHAN PENTING: Kita pakai 'gemini-pro' (1.0) yang paling stabil.
        // 'gemini-1.5-flash' sering error 404 jika akun belum disetting billing/region.
        this.model = "gemini-2.5-flash";
    }

    @Override
    protected String buildPrompt(Disease disease) {
        // Gabungkan string dengan (+) biasa agar aman dari error format %s
        String diseaseName = (disease.getName() != null) ? disease.getName() : "Unknown";
        
        return "You are a nutritionist AI. Patient diagnosis: " + diseaseName + ". " +
               "Provide dietary recommendations in STRICT JSON format. " +
               "NO Markdown, NO ```json wrappers. Just raw JSON.\n\n" +
               "JSON Structure:\n" +
               "{ \"foodsToEat\": [\"item1\", \"item2\", \"item3\"], " +
               "\"foodsToAvoid\": [\"item1\", \"item2\", \"item3\"], " +
               "\"additionalNotes\": \"Brief explanation\" }";
    }

    @Override
    protected String callAI(String prompt) throws Exception {
        // URL Bersih tanpa karakter aneh
        // Format URL untuk Gemini Pro di API v1beta
        this.apiUrl = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + geminiApiKey;

        // Build Request Body
        JsonObject requestBody = new JsonObject();
        JsonArray contents = new JsonArray();
        JsonObject content = new JsonObject();
        JsonArray parts = new JsonArray();
        JsonObject part = new JsonObject();
        
        part.addProperty("text", prompt);
        parts.add(part);
        content.add("parts", parts);
        contents.add(content);
        requestBody.add("contents", contents);

        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");

        // Call API
        String response = apiClient.sendPostRequest(
            this.apiUrl,
            requestBody.toString(),
            headers
        );

        // Parsing Response
        try {
            JsonObject responseJson = JsonParser.parseString(response).getAsJsonObject();
            
            // Cek Error
            if (responseJson.has("error")) {
                throw new Exception("Google AI Error: " + responseJson.get("error").toString());
            }

            JsonArray candidates = responseJson.getAsJsonArray("candidates");
            if (candidates != null && candidates.size() > 0) {
                // Struktur JSON Gemini Pro sedikit berbeda kadang-kadang, kita ambil text-nya
                return candidates.get(0).getAsJsonObject()
                        .getAsJsonObject("content")
                        .getAsJsonArray("parts")
                        .get(0).getAsJsonObject()
                        .get("text").getAsString();
            }
        } catch (Exception e) {
            // Debugging: Jika error, print respon aslinya ke console server
            System.out.println("DEBUG RESPONSE: " + response);
            throw new Exception("Gagal baca respon AI: " + e.getMessage());
        }

        throw new Exception("No content in Gemini response");
    }

    @Override
    protected FoodRecommendation parseResponse(String response, Disease disease) {
        FoodRecommendation recommendation = new FoodRecommendation(disease, getProviderName());

        try {
            String cleanJson = cleanMarkdown(response);
            JsonObject jsonResponse = JsonParser.parseString(cleanJson).getAsJsonObject();

            if (jsonResponse.has("foodsToEat")) {
                JsonArray arr = jsonResponse.getAsJsonArray("foodsToEat");
                for (int i = 0; i < arr.size(); i++) recommendation.addFoodToEat(arr.get(i).getAsString());
            }

            if (jsonResponse.has("foodsToAvoid")) {
                JsonArray arr = jsonResponse.getAsJsonArray("foodsToAvoid");
                for (int i = 0; i < arr.size(); i++) recommendation.addFoodToAvoid(arr.get(i).getAsString());
            }

            if (jsonResponse.has("additionalNotes")) {
                recommendation.setAdditionalNotes(jsonResponse.get("additionalNotes").getAsString());
            }
            
            recommendation.setReason("Generated by " + this.model);

        } catch (Exception e) {
            recommendation.setAdditionalNotes(response);
        }

        return recommendation;
    }

    @Override
    protected String getProviderName() {
        return "Google Gemini (" + this.model + ")";
    }

    private String cleanMarkdown(String text) {
        if (text == null) return "";
        String cleaned = text.trim();
        if (cleaned.startsWith("```json")) cleaned = cleaned.substring(7);
        else if (cleaned.startsWith("```")) cleaned = cleaned.substring(3);
        if (cleaned.endsWith("```")) cleaned = cleaned.substring(0, cleaned.length() - 3);
        return cleaned.trim();
    }
}